// export const SIGN_UP = 'SIGN_UP'
// export const GET_USER_INFO = 'GET_USER_INFO'
// export const LOGGED_IN = 'LOGGED_IN'
// export const SIGN_OUT = 'SIGN_OUT'
// export const SIGN_ERROR = 'SIGN_ERROR'

export default {
  SIGN_UP: 'SIGN_UP',
  GET_USER_INFO: 'GET_USER_INFO',
  LOGGED_IN: 'LOGGED_IN',
  SIGN_OUT: 'SIGN_OUT',
  SIGN_ERROR: 'SIGN_ERROR',
  FETCH_MESSAGE: 'FETCH_MESSAGE',
  POST_WATCHLIST: 'POST_WATCHLIST',
  DELETE_WATCHLIST: 'DELETE_WATCHLIST'
}
